# Generated by Django 5.2.6 on 2025-10-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_job_jobresume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
