# Generated by Django 5.2.6 on 2025-10-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_job_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
