# Generated by Django 5.2.6 on 2026-02-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jobrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
